# Ubuntu Linux as the base image. You can use any version of Ubuntu here
FROM ubuntu:18.04

EXPOSE 8000
# Set UTF-8 encoding
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

WORKDIR /home/user/
# Install Python
RUN apt-get -y update && apt-get install -y && apt-get install -y apt-utils\
    git \
    python3-pip python3-dev \
    software-properties-common
RUN add-apt-repository universe
# The following line ensures that the subsequent install doesn't expect user input
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install python3-pip python3-dev

# Install dependencies
RUN pip3 install --upgrade pip

RUN pip3 install spacy
RUN python3 -m spacy download en_core_web_sm
RUN pip3 install --user -U nltk

RUN pip3 install --upgrade urllib3 awscli

RUN git clone https://github.com/deepset-ai/haystack.git
WORKDIR "/haystack"
RUN pip3 install --upgrade pip
RUN pip3 install '.[colab]'


RUN pip3 install -U scikit-learn

# RUN pip3 install -r requirements.txt
# Add the files into container, under QA folder, modify this based on your need
RUN mkdir /QA
ADD answer /QA

RUN mkdir /QA/saveDocs


# Change the permissions of programs
CMD ["chmod 777 /QA/*"]
# Set working dir as /QA
WORKDIR /QA

ENTRYPOINT ["/bin/bash", "-c"]